### ISSUE TITLE
Client should extend BaseClient

### ISSUE THREAD

**Issue by stevencoulter** [authomize/connectors-rest-api-client#42]
The [Client](https://github.com/authomize/connectors-rest-api-client/blob/master/authomize/rest_api_client/client/client.py) class does not currently extend the [BaseClient](https://github.com/authomize/connectors-rest-api-client/blob/master/authomize/rest_api_client/client/base_client.py) class.  Looking at the GitLab [Authomize Repository](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/), the Client is expected to have [http_get](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/-/blame/main/connectors/__init__.py#L273) and [http_post](https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/authomize/-/blame/main/connectors/__init__.py#L302) methods, which are defined in the BaseClient [here](https://github.com/authomize/connectors-rest-api-client/blob/master/authomize/rest_api_client/client/base_client.py#L24) and [here](https://github.com/authomize/connectors-rest-api-client/blob/master/authomize/rest_api_client/client/base_client.py#L38).

**Comment by RoiAuthomize** [comment]
The GitLab Authomize Repository uses our rest-API V1 which is deprecated, please note the current version of the client support the newer V2 of the API which is much faster, reliable, and supports more features.

The [Client](https://github.com/authomize/connectors-rest-api-client/blob/master/authomize/rest_api_client/client/client.py) exports all V2 endpoints directly without the need to handle transaction lifecycle.

**Comment by jdsalaro** [comment]
> The GitLab Authomize Repository uses our rest-API V1 which is deprecated, please note the current version of the client support the newer V2 of the API which is much faster, reliable, and supports more features.

We're currently relying on the latest version of this repository.

> The [Client](https://github.com/authomize/connectors-rest-api-client/blob/master/authomize/rest_api_client/client/client.py) exports all V2 endpoints directly without the need to handle transaction lifecycle.


Which still relies on the V1 Authomize API for transaction management and as per the README.md V1 transactions seem to be the recommended approach 👇🏼 

https://github.com/authomize/connectors-rest-api-client/blob/master/authomize/rest_api_client/client/connectors_client.py#L73
